// Code generated by "stringer -type=GateType,GateStatus -linecomment"; DO NOT EDIT.

package model

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[TypeUnknown-0]
	_ = x[TypeFacebook-1]
	_ = x[TypeInstagram-2]
	_ = x[TypeWhatsApp-3]
	_ = x[TypeTelegramBot-4]
	_ = x[TypeTelegramApp-5]
}

const _GateType_name = "unknownfacebookinstagramwhatsapptelegram_bottelegram_app"

var _GateType_index = [...]uint8{0, 7, 15, 24, 32, 44, 56}

func (i GateType) String() string {
	if i < 0 || i >= GateType(len(_GateType_index)-1) {
		return "GateType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _GateType_name[_GateType_index[i]:_GateType_index[i+1]]
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[StatusUnknown-0]
	_ = x[StatusActive-1]
	_ = x[StatusDisabled-2]
	_ = x[StatusError-3]
}

const _GateStatus_name = "unknownactivedisablederror"

var _GateStatus_index = [...]uint8{0, 7, 13, 21, 26}

func (i GateStatus) String() string {
	if i < 0 || i >= GateStatus(len(_GateStatus_index)-1) {
		return "GateStatus(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _GateStatus_name[_GateStatus_index[i]:_GateStatus_index[i+1]]
}
